version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8888:8888
    volumes: 
      - .env:/app/.env

  db:
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    
    volumes:
      - ${HOME}/.mongo:/data/db
  
 
    ports:
      - 27017:27017
